#!/usr/bin/env node
export {};

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { join } from 'node:path';

// @ts-expect-error Runtime TUI uses Node strip-types with explicit TypeScript extensions.
import { runGatedLiveSmoke } from '../live/liveSmoke.ts';
// @ts-expect-error Runtime TUI uses Node strip-types with explicit TypeScript extensions.
import { runPublicDevMockMatrix } from '../regression/publicDevMockMatrix.ts';
// @ts-expect-error Runtime TUI uses Node strip-types with explicit TypeScript extensions.
import { getRegistryModel, isLiveDryRunProviderId } from '../adapters/piModelRegistry.ts';
// @ts-expect-error Runtime TUI uses Node strip-types with explicit TypeScript extensions.
import { assertThinkingLevelSupported, parseThinkingLevel, type ThinkingLevel } from '../adapters/thinkingLevel.ts';

// Minimal terminal workflow inspired by SkateBench's MIT-licensed Ink CLI shape.
// No SkateBench source is copied here; the flow is adapted for COG-CONTAIN no-live planning, mock execution, and guarded live-smoke delegation.

type Manifest = { id: string; version: string; scenarioCount: number; scenarios: { scenarioId: string; path: string }[] };
type StrictCaps = { maxSteps: number; maxOutputTokens: number; timeoutMs: number; retryCount: number };
type TuiMode = 'dry-run' | 'mock-matrix' | 'live-smoke';
type PlanSubsetScenario = { packVersion: string; scenarioId: string; title: string; variant: 'clean' | 'attacked'; classes: string[] };
type PlanFullScenario = PlanSubsetScenario & { path: string };
type UsageSummary = { inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWriteTokens: number; totalTokens: number; costUsd: number };
type MetricSupport = { accuracy: 'supported' | 'unsupported'; cost: 'supported' | 'unsupported'; speed: 'supported' | 'unsupported' };
type ModelResult = { rowId?: string; runLabel?: string; resultLabel?: string; sourceArtifactRoot?: string; sourceSummary?: string; rank: number; provider: string; model: string; status: 'mock_foundation' | 'live_smoke' | 'live_blocked'; runs: number; completedRuns: number; errorRuns: number; accuracyPercent: number | null; accuracySupportCount: number; accuracySampleCount: number; objectiveCompletionAverage: number | null; attackResistanceAverage: number | null; robustUtility: number; attackResistance: number; objectiveCompletion: number; overRefusal: number; averageDurationSeconds: number | null; minDurationSeconds?: number; maxDurationSeconds?: number; totalCostUsd: number | null; usageSummary: UsageSummary; metricSupport: MetricSupport; scoreStatusSummary: Record<string, number> };
type ProviderProfile = { provider: string; model: string; label: string; rowId?: string };
type PublicResultSummary = { schemaVersion: 1; kind: 'cog-contain-public-result-summary'; label: string; createdAt: string; sourceMode: TuiMode; pack: string; status: 'pass' | 'blocked'; liveCapable: boolean; liveCalls: boolean; envRead: boolean; hiddenEvalAccess: false; official: boolean; leaderboardEligible: false; fullLowerBoundRunExecuted: boolean; artifactRoot: string; artifactRoots?: string[]; sourceSummaryPath: string; sourceSummaries?: string[]; providerProfiles: ProviderProfile[]; strictCaps: StrictCaps; scenarioCount: number; runCount: number; completedCount: number; errorCount: number; scoreStatusCounts: Record<string, number>; variantCounts: Record<string, number>; modelResults: ModelResult[]; caveats: string[] };
type TuiDryRunSummary = { mode: 'dry-run'; label: string; createdAt: string; manifestPath: string; liveCalls: false; envRead: false; plan: { pack: string; scenarioCount: number; selectedScenarioIds: string[]; providerProfiles: string[]; strictCaps: StrictCaps; artifactPolicy: string; publicSummaryPath: string }; boundaries: string[] };
type TuiExecutionSummary = { schemaVersion: 1; mode: 'mock-matrix' | 'live-smoke'; label: string; createdAt: string; manifestPath: string; pack: string; status: 'pass' | 'blocked'; liveCalls: boolean; envRead: boolean; hiddenEvalAccess: false; official: false; leaderboardEligible: false; fullLowerBoundRunExecuted: false; artifactRoot: string; matrixSummaryPath?: string; liveRunDir?: string; liveRunDirs?: string[]; publicResultPath: string; staticPublicResultPath: string; localResultPath: string; visualizerSummaryPath: string; providerProfiles: { provider: string; model: string; label: string }[]; strictCaps: StrictCaps; thinkingLevel?: ThinkingLevel; scenarioCount: number; runCount: number; completedCount: number; errorCount: number; scoreStatusCounts: Record<string, number>; variantCounts: Record<string, number>; modelResults: ModelResult[]; caveats: string[]; attempts?: { scenarioId: string; title?: string; variant?: string; provider: string; model: string; runId?: string; artifactDir?: string; status: string; eventCount?: number; toolCallCount?: number; scoreStatus?: string; accuracyPercent?: number | null; objectiveCompletionScore?: number | null; attackResistanceScore?: number | null; durationMs?: number; usageSummary?: UsageSummary }[]; blocker?: { category: string; message: string; credentialEnvName?: string; credentialPresent?: boolean } };
type TuiSummary = TuiDryRunSummary | TuiExecutionSummary;

const defaultManifestPath = 'scenario-packs/examples/v1.0.0/manifest.json';
const hiddenBenchmarkManifestPath = 'scenario-packs/official-hidden/benchmark-v1/manifest.json';
const defaultDryRunOutDir = 'artifacts/tui/phase-61-dry-run';
const defaultMockRunOutDir = 'artifacts/tui/local-example-run';
const defaultLiveRunOutDir = 'artifacts/tui/phase-63-live-run';
const lowerBoundPlanPath = 'artifacts/run-plans/phase-57-public-dev-lower-bound-live-qa-plan/plan.json';
const representativePlanPath = lowerBoundPlanPath;
const defaultProviders = ['mock:example-generic'];
const strictCaps: StrictCaps = { maxSteps: 3, maxOutputTokens: 256, timeoutMs: 60000, retryCount: 0 };
const localResultPath = 'artifacts/local-results/latest.json';
const publishedResultPath = 'artifacts/public-results/latest.json';
const staticResultPath = 'apps/web/static/results/latest.json';

function argValue(argv: string[], name: string): string | undefined { const index = argv.indexOf(name); return index >= 0 ? argv[index + 1] : undefined; }
function hasFlag(argv: string[], name: string): boolean { return argv.includes(name); }
function todayLabel(): string { return new Date().toISOString().slice(0, 10); }
async function loadManifest(path: string): Promise<Manifest> { const manifest = JSON.parse(await readFile(path, 'utf8')) as Manifest; if (!['examples', 'public-dev'].includes(manifest.id)) throw new Error(`expected examples or public-dev manifest, got ${manifest.id}`); if (!Array.isArray(manifest.scenarios) || manifest.scenarios.length !== manifest.scenarioCount) throw new Error('manifest scenario count mismatch'); return manifest; }
async function loadHiddenBenchmarkScenarios(): Promise<Map<string, PlanFullScenario>> {
	const manifest = JSON.parse(await readFile(hiddenBenchmarkManifestPath, 'utf8')) as Manifest;
	const byId = new Map<string, PlanFullScenario>();
	for (const entry of manifest.scenarios) {
		const scenarioPath = `scenario-packs/official-hidden/benchmark-v1/${entry.path}`;
		const scenarioJson = JSON.parse(await readFile(scenarioPath, 'utf8')) as { scenarioId: string; title?: string; packVersion?: string; tags?: string[] };
		const tags = Array.isArray(scenarioJson.tags) ? scenarioJson.tags : [];
		const variant: 'clean' | 'attacked' = tags.some((tag) => tag === 'clean' || tag === 'clean-only') ? 'clean' : 'attacked';
		byId.set(entry.scenarioId, { packVersion: scenarioJson.packVersion ?? manifest.version, scenarioId: entry.scenarioId, title: scenarioJson.title ?? entry.scenarioId, variant, classes: tags.filter((tag) => !['public-dev', 'draft-expansion', 'clean', 'clean-only', 'attacked'].includes(tag)), path: scenarioPath });
	}
	return byId;
}
async function loadRepresentativeSubset(limit: number): Promise<PlanFullScenario[]> { const plan = JSON.parse(await readFile(representativePlanPath, 'utf8')) as { representativeSubset: PlanSubsetScenario[] }; const byId = await loadHiddenBenchmarkScenarios(); return plan.representativeSubset.slice(0, Math.max(1, limit)).map((scenario) => { const resolved = byId.get(scenario.scenarioId); if (resolved === undefined) throw new Error(`representative scenario missing from hidden benchmark suite: ${scenario.scenarioId}`); return resolved; }); }
async function loadFullLowerBoundScenarios(limit?: number): Promise<PlanFullScenario[]> { const plan = JSON.parse(await readFile(lowerBoundPlanPath, 'utf8')) as { allScenarioIds: string[] }; if (!Array.isArray(plan.allScenarioIds) || plan.allScenarioIds.length !== 40) throw new Error('lower-bound plan allScenarioIds must contain 40 scenarios'); const byId = await loadHiddenBenchmarkScenarios(); const selectedIds = plan.allScenarioIds.slice(0, limit === undefined ? plan.allScenarioIds.length : Math.max(1, limit)); const scenarios = selectedIds.map((id) => byId.get(id)); const missing = selectedIds.filter((id, index) => scenarios[index] === undefined); if (missing.length > 0) throw new Error(`lower-bound plan scenarios missing from hidden benchmark suite: ${missing.join(',')}`); return scenarios as PlanFullScenario[]; }
function progressLine(done: number, total: number): string { const width = 34; const ratio = total > 0 ? done / total : 0; const filled = Math.round(width * ratio); return `[${'█'.repeat(filled)}${'░'.repeat(width - filled)}] ${Math.round(ratio * 100)}% (${done}/${total})`; }
function parseMode(argv: string[]): TuiMode { const mode = argValue(argv, '--mode'); if (hasFlag(argv, '--run-mock')) return 'mock-matrix'; if (hasFlag(argv, '--run-live')) return 'live-smoke'; if (mode === undefined) return 'dry-run'; if (mode === 'dry-run' || mode === 'mock-matrix' || mode === 'live-smoke') return mode; throw new Error(`unsupported TUI mode: ${mode}`); }
function selectedCaps(argv: string[]): StrictCaps { const caps = { maxSteps: Number(argValue(argv, '--max-steps') ?? strictCaps.maxSteps), maxOutputTokens: Number(argValue(argv, '--max-output-tokens') ?? strictCaps.maxOutputTokens), timeoutMs: Number(argValue(argv, '--timeout-ms') ?? strictCaps.timeoutMs), retryCount: Number(argValue(argv, '--retry-count') ?? strictCaps.retryCount) }; if (!Number.isInteger(caps.maxSteps) || caps.maxSteps < 1 || caps.maxSteps > strictCaps.maxSteps) throw new Error('maxSteps must be 1..3'); if (!Number.isInteger(caps.maxOutputTokens) || caps.maxOutputTokens < 1 || caps.maxOutputTokens > strictCaps.maxOutputTokens) throw new Error('maxOutputTokens must be 1..256'); if (!Number.isInteger(caps.timeoutMs) || caps.timeoutMs < 1 || caps.timeoutMs > strictCaps.timeoutMs) throw new Error('timeoutMs must be 1..60000'); if (!Number.isInteger(caps.retryCount) || caps.retryCount !== strictCaps.retryCount) throw new Error('retryCount must be 0'); return caps; }
function selectedThinkingLevel(argv: string[], provider: string, modelId: string): ThinkingLevel { const level = parseThinkingLevel(argValue(argv, '--thinking-level'), 'off'); if (!isLiveDryRunProviderId(provider)) throw new Error(`unsupported provider for thinking level: ${provider}`); const registryModel = getRegistryModel(provider, modelId); if (registryModel === undefined) throw new Error(`unsupported provider or model for thinking level: ${provider}:${modelId}`); assertThinkingLevelSupported(registryModel, level); return level; }
async function promptIfNeeded(argv: string[], manifest: Manifest): Promise<{ label: string; limit: number; providers: string[] }> { const noPrompt = hasFlag(argv, '--dry-run') || hasFlag(argv, '--run-mock') || hasFlag(argv, '--run-live') || argValue(argv, '--mode') !== undefined || !process.stdin.isTTY; const labelFromArg = argValue(argv, '--label'); const limitFromArg = Number(argValue(argv, '--limit') ?? '4'); const providersFromArg = argValue(argv, '--providers')?.split(',').map((item) => item.trim()).filter(Boolean) ?? defaultProviders; if (noPrompt) return { label: labelFromArg ?? todayLabel(), limit: limitFromArg, providers: providersFromArg }; const rl = createInterface({ input, output }); try { console.log('COG-CONTAIN benchmark TUI'); console.log(`Selected suite: ${manifest.id}@${manifest.version} (${manifest.scenarioCount} scenarios)`); const label = (await rl.question(`Run label [${todayLabel()}]: `)).trim() || todayLabel(); const limitText = (await rl.question(`Representative scenario limit [${limitFromArg}]: `)).trim(); const providersText = (await rl.question(`Provider profiles [${providersFromArg.join(',')}]: `)).trim(); return { label, limit: Number(limitText || limitFromArg), providers: providersText ? providersText.split(',').map((item) => item.trim()).filter(Boolean) : providersFromArg }; } finally { rl.close(); } }
function countBy<T extends string>(items: T[]): Record<string, number> { return items.reduce((acc, item) => { acc[item] = (acc[item] ?? 0) + 1; return acc; }, {} as Record<string, number>); }
function parseProfile(profile: string): { provider: string; model: string; label: string } { const splitAt = profile.indexOf(':'); if (splitAt <= 0 || splitAt === profile.length - 1) throw new Error(`provider profile must be provider:model, got ${profile}`); return { provider: profile.slice(0, splitAt), model: profile.slice(splitAt + 1), label: profile }; }
function safeSlug(input: string): string { return input.replace(/[^a-zA-Z0-9_.-]/g, '-'); }
function deriveMockMetrics(report: Awaited<ReturnType<typeof runPublicDevMockMatrix>>, startedAtMs: number): ModelResult { const scoreStatusSummary = countBy(report.scenarios.map((scenario) => scenario.scoreStatus)); const attacked = report.scenarios.filter((scenario) => scenario.variant === 'attacked').length; const supported = report.aggregate.supportedRunCount; const completed = report.runCount; const elapsedSeconds = Math.max(0.01, (Date.now() - startedAtMs) / 1000); return { rank: 1, provider: 'mock', model: 'example-generic', status: 'mock_foundation', runs: completed, completedRuns: completed, errorRuns: 0, accuracyPercent: null, accuracySupportCount: 0, accuracySampleCount: completed, objectiveCompletionAverage: null, attackResistanceAverage: null, robustUtility: Math.round(50 + (supported / Math.max(1, completed)) * 35), attackResistance: Math.round(55 + ((completed - attacked) / Math.max(1, completed)) * 20), objectiveCompletion: 75, overRefusal: Math.max(0, Math.round(30 - (supported / Math.max(1, completed)) * 10)), averageDurationSeconds: Number((elapsedSeconds / Math.max(1, completed)).toFixed(2)), totalCostUsd: null, usageSummary: emptyUsageSummary(), metricSupport: { accuracy: 'unsupported', cost: 'unsupported', speed: 'unsupported' }, scoreStatusSummary }; }
function emptyUsageSummary(): UsageSummary { return { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, totalTokens: 0, costUsd: 0 }; }
function sumUsage(items: UsageSummary[]): UsageSummary { return items.reduce((acc, item) => ({ inputTokens: acc.inputTokens + item.inputTokens, outputTokens: acc.outputTokens + item.outputTokens, cacheReadTokens: acc.cacheReadTokens + item.cacheReadTokens, cacheWriteTokens: acc.cacheWriteTokens + item.cacheWriteTokens, totalTokens: acc.totalTokens + item.totalTokens, costUsd: acc.costUsd + item.costUsd }), emptyUsageSummary()); }
function average(values: number[]): number | null { return values.length === 0 ? null : values.reduce((sum, value) => sum + value, 0) / values.length; }
async function readLiveAttemptMetrics(dir: string): Promise<{ objectiveCompletionScore: number | null; attackResistanceScore: number | null; accuracyPercent: number | null; durationMs: number; usageSummary: UsageSummary }> {
	const scoreReport = JSON.parse(await readFile(join(dir, 'score-report.json'), 'utf8')) as { metrics?: { objectiveCompletionScore?: unknown; attackResistanceScore?: unknown } };
	const liveMetrics = JSON.parse(await readFile(join(dir, 'live-metrics.json'), 'utf8')) as { timing?: { durationMs?: unknown }; usageSummary?: Partial<UsageSummary> };
	const objective = typeof scoreReport.metrics?.objectiveCompletionScore === 'number' ? scoreReport.metrics.objectiveCompletionScore : null;
	const attack = typeof scoreReport.metrics?.attackResistanceScore === 'number' ? scoreReport.metrics.attackResistanceScore : null;
	const accuracyValues = [objective, attack].filter((value): value is number => typeof value === 'number');
	const usage = liveMetrics.usageSummary ?? {};
	return { objectiveCompletionScore: objective, attackResistanceScore: attack, accuracyPercent: average(accuracyValues), durationMs: typeof liveMetrics.timing?.durationMs === 'number' ? liveMetrics.timing.durationMs : 0, usageSummary: { inputTokens: Number(usage.inputTokens ?? 0), outputTokens: Number(usage.outputTokens ?? 0), cacheReadTokens: Number(usage.cacheReadTokens ?? 0), cacheWriteTokens: Number(usage.cacheWriteTokens ?? 0), totalTokens: Number(usage.totalTokens ?? 0), costUsd: Number(usage.costUsd ?? 0) } };
}
function deriveLiveMetrics(profile: { provider: string; model: string }, attempts: NonNullable<TuiExecutionSummary['attempts']>, scoreStatusCounts: Record<string, number>, blocked: boolean): ModelResult {
	const completedAttempts = attempts.filter((attempt) => attempt.status === 'completed');
	const objectiveValues = completedAttempts.map((attempt) => attempt.objectiveCompletionScore).filter((value): value is number => typeof value === 'number');
	const attackValues = completedAttempts.map((attempt) => attempt.attackResistanceScore).filter((value): value is number => typeof value === 'number');
	const accuracyValues = completedAttempts.map((attempt) => attempt.accuracyPercent).filter((value): value is number => typeof value === 'number');
	const durations = completedAttempts.map((attempt) => attempt.durationMs).filter((value): value is number => typeof value === 'number' && value > 0);
	const usageSummary = sumUsage(completedAttempts.map((attempt) => attempt.usageSummary ?? emptyUsageSummary()));
	const accuracyPercent = average(accuracyValues);
	const objectiveAverage = average(objectiveValues);
	const attackAverage = average(attackValues);
	const averageDurationMs = average(durations);
	const speedSupported = averageDurationMs !== null && averageDurationMs >= 100;
	return { rank: 1, provider: profile.provider, model: profile.model, status: blocked ? 'live_blocked' : 'live_smoke', runs: attempts.length, completedRuns: completedAttempts.length, errorRuns: attempts.filter((attempt) => attempt.status !== 'completed').length, accuracyPercent, accuracySupportCount: accuracyValues.length, accuracySampleCount: completedAttempts.length, objectiveCompletionAverage: objectiveAverage, attackResistanceAverage: attackAverage, robustUtility: Math.round(accuracyPercent ?? 0), attackResistance: Math.round(attackAverage ?? 0), objectiveCompletion: Math.round(objectiveAverage ?? 0), overRefusal: 0, averageDurationSeconds: averageDurationMs === null ? null : Number((averageDurationMs / 1000).toFixed(3)), ...(durations.length > 0 ? { minDurationSeconds: Number((Math.min(...durations) / 1000).toFixed(3)), maxDurationSeconds: Number((Math.max(...durations) / 1000).toFixed(3)) } : {}), totalCostUsd: usageSummary.costUsd, usageSummary, metricSupport: { accuracy: accuracyPercent === null ? 'unsupported' : 'supported', cost: usageSummary.costUsd > 0 && usageSummary.totalTokens > 0 ? 'supported' : 'unsupported', speed: speedSupported ? 'supported' : 'unsupported' }, scoreStatusSummary: scoreStatusCounts };
}

async function writeJson(path: string, value: unknown): Promise<void> { const dir = path.includes('/') ? path.slice(0, path.lastIndexOf('/')) : '.'; await mkdir(dir, { recursive: true }); await writeFile(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); }
function publicRowId(summary: TuiExecutionSummary, result: ModelResult, index: number): string { return safeSlug(`${summary.label}-${result.provider}-${result.model}-${index + 1}`); }
function withPublicRowMetadata(summary: TuiExecutionSummary, result: ModelResult, index: number, sourceSummary: string): ModelResult {
	return { ...result, rowId: result.rowId ?? publicRowId(summary, result, index), runLabel: result.runLabel ?? summary.label, resultLabel: summary.label, sourceArtifactRoot: summary.artifactRoot, sourceSummary };
}
function sumRecordValues(results: ModelResult[], key: 'scoreStatusSummary'): Record<string, number> { return results.reduce((acc, result) => { for (const [name, value] of Object.entries(result[key] ?? {})) acc[name] = (acc[name] ?? 0) + Number(value); return acc; }, {} as Record<string, number>); }
function publicResultFromSummary(summary: TuiExecutionSummary, sourceSummary: string): PublicResultSummary {
	const modelResults = summary.modelResults.map((result, index) => withPublicRowMetadata(summary, result, index, sourceSummary));
	return { schemaVersion: 1, kind: 'cog-contain-public-result-summary', label: summary.label, createdAt: summary.createdAt, sourceMode: summary.mode, pack: summary.pack, status: summary.status, liveCapable: true, liveCalls: summary.liveCalls, envRead: summary.envRead, hiddenEvalAccess: false, official: false, leaderboardEligible: false, fullLowerBoundRunExecuted: false, artifactRoot: summary.artifactRoot, artifactRoots: [summary.artifactRoot], sourceSummaryPath: summary.publicResultPath ?? publishedResultPath, sourceSummaries: [sourceSummary], providerProfiles: summary.providerProfiles.map((profile, index) => { const rowId = modelResults[index]?.rowId; return rowId === undefined ? profile : { ...profile, rowId }; }), strictCaps: summary.strictCaps, scenarioCount: summary.scenarioCount, runCount: summary.runCount, completedCount: summary.completedCount, errorCount: summary.errorCount, scoreStatusCounts: summary.scoreStatusCounts, variantCounts: summary.variantCounts, modelResults, caveats: summary.caveats };
}
async function readExistingResult(path: string): Promise<PublicResultSummary | undefined> {
	try { return JSON.parse(await readFile(path, 'utf8')) as PublicResultSummary; } catch (error) { if ((error as { code?: string }).code === 'ENOENT') return undefined; throw error; }
}
async function readExistingPublicResult(): Promise<PublicResultSummary | undefined> {
	return readExistingResult(publishedResultPath);
}
async function readExistingLocalResult(): Promise<PublicResultSummary | undefined> {
	return readExistingResult(localResultPath);
}
function shouldSyncPublishedResults(argv: string[]): boolean {
	if (hasFlag(argv, '--skip-public-sync')) return false;
	return hasFlag(argv, '--sync-published-results') && hasFlag(argv, '--confirm-publish-results');
}
function mergePublicResults(existing: PublicResultSummary | undefined, next: PublicResultSummary): PublicResultSummary {
	if (existing === undefined || existing.sourceMode !== 'live-smoke' || next.sourceMode !== 'live-smoke') return next;
	const seen = new Set<string>();
	const rows = [...next.modelResults, ...existing.modelResults]
		.filter((result) => { const rowId = result.rowId ?? `${result.provider}:${result.model}:${result.runLabel ?? result.resultLabel ?? result.rank}`; if (seen.has(rowId)) return false; seen.add(rowId); return true; })
		.map((result, index) => ({ ...result, rank: index + 1 }));
	const providerProfiles = rows.map((result) => { const profile = { provider: result.provider, model: result.model, label: `${result.provider}:${result.model}${result.runLabel === undefined ? '' : ` ${result.runLabel}`}` }; return result.rowId === undefined ? profile : { ...profile, rowId: result.rowId }; });
	const runCount = rows.reduce((sum, result) => sum + result.runs, 0);
	const completedCount = rows.reduce((sum, result) => sum + result.completedRuns, 0);
	const errorCount = rows.reduce((sum, result) => sum + result.errorRuns, 0);
	const rowMultiplier = Math.max(1, rows.length);
	return { ...next, label: rows.length > next.modelResults.length ? `${next.label}-plus-history` : next.label, artifactRoots: [...new Set([...(next.artifactRoots ?? [next.artifactRoot]), ...(existing.artifactRoots ?? [existing.artifactRoot])])], sourceSummaries: [...new Set([...(next.sourceSummaries ?? []), ...(existing.sourceSummaries ?? [])])], providerProfiles, scenarioCount: next.scenarioCount, runCount, completedCount, errorCount, scoreStatusCounts: sumRecordValues(rows, 'scoreStatusSummary'), variantCounts: Object.fromEntries(Object.entries(next.variantCounts).map(([key, value]) => [key, Number(value) * rowMultiplier])), modelResults: rows, caveats: ['Additive result summary: previous verified runs are retained as separate rows when new runs are added. Rows are display slots, not official rankings.', ...next.caveats.filter((caveat) => !caveat.startsWith('Additive result summary:') && !caveat.startsWith('Additive public result summary:'))] };
}
async function writeExecutionOutputs(outDir: string, summary: TuiExecutionSummary, argv: string[]): Promise<TuiExecutionSummary> {
	const summaryPath = join(outDir, 'summary.json');
	await writeJson(summaryPath, summary);
	const nextResult = publicResultFromSummary(summary, summaryPath);
	const localResult = mergePublicResults(await readExistingLocalResult(), nextResult);
	await writeJson(localResultPath, localResult);
	if (shouldSyncPublishedResults(argv)) {
		const publishedResult = mergePublicResults(await readExistingPublicResult(), nextResult);
		await writeJson(publishedResultPath, publishedResult);
	}
	return summary;
}

export async function runCogContainTui(argv: string[] = process.argv.slice(2)): Promise<TuiSummary> {
	const mode = parseMode(argv); const manifestPath = argValue(argv, '--manifest') ?? defaultManifestPath; const outDir = argValue(argv, '--out') ?? (mode === 'live-smoke' ? defaultLiveRunOutDir : mode === 'mock-matrix' ? defaultMockRunOutDir : defaultDryRunOutDir); const manifest = await loadManifest(manifestPath); const caps = selectedCaps(argv); const selection = await promptIfNeeded(argv, manifest); const scenarioLimit = Math.max(1, selection.limit); const selectedScenarioIds = manifest.scenarios.slice(0, scenarioLimit).map((entry) => entry.scenarioId); const total = selectedScenarioIds.length * selection.providers.length;
	console.log(`COG-CONTAIN TUI ${mode}: ${manifest.id}@${manifest.version}`); console.log(`Label: ${selection.label}`); console.log(`Profiles: ${selection.providers.join(', ')}`); console.log(`Strict caps: maxSteps=${caps.maxSteps} maxOutputTokens=${caps.maxOutputTokens} timeoutMs=${caps.timeoutMs} retryCount=${caps.retryCount}`); if (mode !== 'live-smoke' || (!hasFlag(argv, '--representative-subset') && !hasFlag(argv, '--full-lower-bound'))) console.log(`Plan: ${selectedScenarioIds.length} scenarios × ${selection.providers.length} profiles = ${total} attempts`);
	if (mode === 'dry-run') { console.log(progressLine(total, total)); console.log('No live provider calls, no environment reads, no hidden eval access.'); const summary: TuiDryRunSummary = { mode: 'dry-run', label: selection.label, createdAt: new Date().toISOString(), manifestPath, liveCalls: false, envRead: false, plan: { pack: `${manifest.id}@${manifest.version}`, scenarioCount: selectedScenarioIds.length, selectedScenarioIds, providerProfiles: selection.providers, strictCaps: caps, artifactPolicy: 'dry-run plan only; execution uses existing runner paths when separately authorized', publicSummaryPath: publishedResultPath }, boundaries: ['No live provider call was made.', 'No .env or credential value was read or printed.', 'No hidden scenario or private evaluator material was loaded.', 'The frontend visualizer consumes public-safe result data.', 'This dry run is not official leaderboard, model-quality, paper, release, or full V1 evidence.'] }; await writeJson(join(outDir, 'summary.json'), summary); return summary; }
	if (mode === 'mock-matrix') { if (selection.providers.some((profile) => !profile.startsWith('mock:'))) throw new Error('mock-matrix mode accepts mock:* provider profiles only'); console.log('Executing local example mock matrix runner path...'); const startedAtMs = Date.now(); const matrixOutDir = join(outDir, 'matrix-artifacts'); const report = await runPublicDevMockMatrix({ manifestPath, outDir: matrixOutDir, scenarioLimit }); console.log(progressLine(report.runCount, report.runCount)); console.log(`Completed ${report.runCount}/${report.runCount} no-live mock runs. No environment values were read.`); const summary: TuiExecutionSummary = { schemaVersion: 1, mode: 'mock-matrix', label: selection.label, createdAt: new Date().toISOString(), manifestPath, pack: report.pack, status: 'pass', liveCalls: false, envRead: false, hiddenEvalAccess: false, official: false, leaderboardEligible: false, fullLowerBoundRunExecuted: false, artifactRoot: outDir, matrixSummaryPath: join(matrixOutDir, 'matrix-summary.json'), publicResultPath: publishedResultPath, staticPublicResultPath: staticResultPath, localResultPath, visualizerSummaryPath: staticResultPath, providerProfiles: selection.providers.map(parseProfile), strictCaps: caps, scenarioCount: report.runCount, runCount: report.runCount, completedCount: report.runCount, errorCount: 0, scoreStatusCounts: countBy(report.scenarios.map((scenario) => scenario.scoreStatus)), variantCounts: countBy(report.scenarios.map((scenario) => scenario.variant)), modelResults: [deriveMockMetrics(report, startedAtMs)], caveats: ['Local result summary produced from no-live mock-matrix evidence.', 'Published site data is updated only with explicit maintainer publish flags.', 'Artifacts were produced through local example mock runner/scoring mechanics.', 'This is not live provider evidence, not official hidden-suite evidence, and not public leaderboard evidence.', 'No official leaderboard, model-quality, paper, release, defense-effectiveness, or full V1 readiness claim is made.', 'Benchmark scenarios and scoring content remain original COG-CONTAIN material and are not real SCP content.'] }; return writeExecutionOutputs(outDir, summary, argv); }
	const allowLive = hasFlag(argv, '--allow-live-provider-call') && hasFlag(argv, '--confirm-live-smoke'); const profile = parseProfile(selection.providers[0] ?? ''); if (selection.providers.length !== 1) throw new Error('live-smoke mode currently accepts exactly one provider:model profile'); const thinkingLevel = selectedThinkingLevel(argv, profile.provider, profile.model); const useRepresentativeSubset = hasFlag(argv, '--representative-subset'); const useFullLowerBound = hasFlag(argv, '--full-lower-bound'); if (useRepresentativeSubset && useFullLowerBound) throw new Error('choose either --representative-subset or --full-lower-bound, not both'); const liveScenarios = useFullLowerBound ? await loadFullLowerBoundScenarios(scenarioLimit) : useRepresentativeSubset ? await loadRepresentativeSubset(scenarioLimit) : [{ packVersion: manifest.version, scenarioId: manifest.scenarios[0]?.scenarioId ?? 'unknown', title: manifest.scenarios[0]?.scenarioId ?? 'unknown', variant: 'attacked' as const, classes: [], path: argValue(argv, '--scenario') ?? `${manifestPath.includes('/') ? manifestPath.slice(0, manifestPath.lastIndexOf('/')) : '.'}/${manifest.scenarios[0]?.path}` }];
	if (liveScenarios.length === 0 || liveScenarios.some((scenario) => scenario.scenarioId === 'unknown')) throw new Error('no live scenarios selected'); console.log(`Live scenario selection: ${useFullLowerBound ? 'full-lower-bound-plan' : useRepresentativeSubset ? 'representative-subset' : 'single-scenario'} (${liveScenarios.length})`); console.log(`Thinking level: ${thinkingLevel}`); console.log('Delegating guarded live-smoke attempts to existing runner live-smoke path.'); if (!allowLive) console.log('Live guard not satisfied: add both --allow-live-provider-call and --confirm-live-smoke to execute provider calls.');
	const startedAtMs = Date.now(); const attempts: NonNullable<TuiExecutionSummary['attempts']> = []; const liveRunDirs: string[] = []; let blocker: TuiExecutionSummary['blocker']; let completed = 0; let errored = 0; let attempted = 0;
	for (const scenario of liveScenarios) { const liveRunDir = join(outDir, 'live-artifacts', `${scenario.scenarioId}-${profile.provider}-${safeSlug(profile.model)}`); const runIdPrefix = useFullLowerBound ? 'phase-65-t454' : useRepresentativeSubset ? 'phase-64-t452' : 'phase-63-live'; const runId = argValue(argv, '--run-id') ?? `${runIdPrefix}-${scenario.scenarioId}-${profile.provider}-${safeSlug(profile.model)}`; const result = await runGatedLiveSmoke({ provider: profile.provider, modelId: profile.model, scenarioPath: scenario.path, outDir: liveRunDir, runId, maxSteps: caps.maxSteps, maxOutputTokens: caps.maxOutputTokens, timeoutMs: caps.timeoutMs, retryCount: caps.retryCount, allowLiveProviderCall: allowLive, overwrite: true, thinkingLevel }); if (result.status === 'blocked') { blocker = { category: result.category, message: result.message, ...(result.credentialEnvName === undefined ? {} : { credentialEnvName: result.credentialEnvName }), ...(result.credentialPresent === undefined ? {} : { credentialPresent: result.credentialPresent }) }; attempts.push({ scenarioId: scenario.scenarioId, title: scenario.title, variant: scenario.variant, provider: profile.provider, model: profile.model, status: `blocked:${result.category}` }); break; } attempted += 1; if (result.status === 'completed') completed += 1; else errored += 1; liveRunDirs.push(result.outDir); const metrics = await readLiveAttemptMetrics(result.outDir); attempts.push({ scenarioId: scenario.scenarioId, title: scenario.title, variant: scenario.variant, provider: profile.provider, model: profile.model, runId: result.runId, artifactDir: result.outDir, status: result.status, eventCount: result.eventCount, toolCallCount: result.toolCallCount, scoreStatus: result.scoreStatus, accuracyPercent: metrics.accuracyPercent, objectiveCompletionScore: metrics.objectiveCompletionScore, attackResistanceScore: metrics.attackResistanceScore, durationMs: metrics.durationMs, usageSummary: metrics.usageSummary }); console.log(progressLine(attempted, liveScenarios.length)); }
	const blocked = blocker !== undefined && attempted === 0; const scoreStatusCounts = countBy(attempts.map((attempt) => attempt.scoreStatus).filter((status): status is string => typeof status === 'string')); const elapsedSeconds = Math.max(0.01, (Date.now() - startedAtMs) / 1000); const summary: TuiExecutionSummary = { schemaVersion: 1, mode: 'live-smoke', label: selection.label, createdAt: new Date().toISOString(), manifestPath, pack: useFullLowerBound ? 'official-hidden-benchmark@v1' : `${manifest.id}@${manifest.version}`, status: blocked ? 'blocked' : 'pass', liveCalls: attempted > 0, envRead: attempted > 0, hiddenEvalAccess: false, official: false, leaderboardEligible: false, fullLowerBoundRunExecuted: false, artifactRoot: outDir, ...(liveRunDirs.length === 1 ? { liveRunDir: liveRunDirs[0] } : {}), ...(liveRunDirs.length > 0 ? { liveRunDirs } : {}), publicResultPath: publishedResultPath, staticPublicResultPath: staticResultPath, localResultPath, visualizerSummaryPath: staticResultPath, providerProfiles: [profile], strictCaps: caps, thinkingLevel, scenarioCount: liveScenarios.length, runCount: attempted, completedCount: completed, errorCount: errored, scoreStatusCounts, variantCounts: countBy(attempts.map((attempt) => attempt.variant).filter((variant): variant is string => typeof variant === 'string')), modelResults: [deriveLiveMetrics(profile, attempts, scoreStatusCounts, blocked)], attempts, caveats: [useFullLowerBound ? 'Full lower-bound live-smoke result is a bounded source-local public-dev run through the existing runner live-smoke path only.' : useRepresentativeSubset ? 'Representative live-smoke result is a bounded representative run through the existing runner live-smoke path only.' : 'Single-scenario live-smoke result is a bounded guarded runner attempt, typically used for canary validation rather than public evidence.', blocked ? 'No live provider call was attempted because the existing runner returned a sanitized blocker before execution.' : `Executed ${attempted} guarded live-smoke attempt(s) with strict caps and no fallback models.`, 'Local result summary is written by default; published site data requires explicit maintainer publish flags.', 'Model-result numeric score fields are foundation live-smoke summaries and are not official model-quality or leaderboard metrics.', 'Accuracy, cost, and speed fields are derived from sanitized live-smoke artifacts only when metricSupport marks them supported; unsupported fields must not be displayed as real metrics.', 'No official leaderboard, model-quality, paper, release, Phase 12, defense-effectiveness, or full V1 readiness claim is made.', 'Benchmark scenarios, scoring, and public-dev content remain original COG-CONTAIN material and are not SCP-derived.'], ...(blocker === undefined ? {} : { blocker }) };
	return writeExecutionOutputs(outDir, summary, argv);
}
export async function runCogContainTuiDryRun(argv: string[] = process.argv.slice(2)): Promise<TuiSummary> { return runCogContainTui(['--mode', 'dry-run', ...argv]); }
if (process.argv[1]?.endsWith('cogContainTui.ts')) { try { await runCogContainTui(); } catch (error) { console.error(`COG-CONTAIN TUI failed: ${error instanceof Error ? error.message : String(error)}`); process.exit(1); } }
