import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { buildPublicSiteSnapshot } from '../src/lib/skatebench/visualizerData.ts';

const artifactUrl = new URL('../../../artifacts/public-results/latest.json', import.meta.url);
const staticResultUrl = new URL('../static/results/latest.json', import.meta.url);
const siteSnapshotUrl = new URL('../src/lib/skatebench/siteResultSnapshot.ts', import.meta.url);

function serializePublicSiteSnapshot(snapshot: ReturnType<typeof buildPublicSiteSnapshot>): string {
	const json = JSON.stringify(snapshot, null, '\t');
	return `// Generated by scripts/preparePublicSite.ts from artifacts/public-results/latest.json.\n// Do not edit manually; rerun prepare-public-site after updating official results.\nimport type { PublicSiteSnapshot } from './visualizerData';\n\nexport const publicSiteSnapshot: PublicSiteSnapshot = ${json};\n`;
}

const artifact = JSON.parse(await readFile(artifactUrl, 'utf8')) as Parameters<typeof buildPublicSiteSnapshot>[0];
if (artifact.kind !== 'cog-contain-public-result-summary') throw new Error('invalid public result kind');
if (artifact.official !== true || artifact.hiddenEvalAccess !== false) {
	throw new Error('public site preparation requires official published result flags');
}
if (artifact.leaderboardEligible === true && artifact.scoreKind !== 'leaderboard-score-v1') {
	throw new Error('leaderboardEligible requires scoreKind leaderboard-score-v1');
}

const publicSiteSnapshot = buildPublicSiteSnapshot(artifact);

await mkdir(new URL('../static/results', import.meta.url), { recursive: true });
await writeFile(staticResultUrl, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
await writeFile(siteSnapshotUrl, serializePublicSiteSnapshot(publicSiteSnapshot), 'utf8');

console.log(
	`prepare public site: ok copied artifacts/public-results/latest.json to static/results/latest.json and regenerated siteResultSnapshot.ts (models=${publicSiteSnapshot.results.map((r) => `${r.provider}:${r.model}`).join(', ')})`
);
